FROM golang:1.22.3-alpine3.20 as service-image
ENV CGO_ENABLED=0
ARG ARG_ENV

COPY . /service

WORKDIR /service

RUN go build -ldflags "-X main.ARG_ENV=${ARG_ENV}"

# Run the Go Binary in Alpine.
FROM alpine:3.20
ARG ARG_ENV

COPY --from=service-image /service/service /service/service
WORKDIR /service
CMD ["./service"]
